[package]
name = "forkfs"
version = "0.1.0"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "ForkFS allows you to isolate a process's changes to your files, sandboxing those changes into another directory."
repository = "https://github.com/SUPERCILEX/forkfs"
keywords = ["tools", "isolate", "files"]
categories = ["command-line-utilities", "development-tools", "development-tools::debugging", "filesystem"]

[dependencies]
anyhow = "1.0.44"
clap-verbosity-flag = "0.3.2"
derive-new = "0.5.9"
dirs = "4.0.0"
exitcode = "1.1.2"
log = "0.4.14"
nix = "0.23.0"
path-absolutize = "3.0.11"
radix_trie = "0.2.1"
sanitize-filename = "0.3.0"
simple_logger = "1.13.0"
structopt = "0.3.25"
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
