[package]
name = "forkfs"
version = "0.2.5"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "ForkFS allows you to sandbox a process's changes to your file system."
repository = "https://github.com/SUPERCILEX/forkfs"
keywords = ["tools", "isolate", "files"]
categories = ["command-line-utilities", "development-tools", "development-tools::debugging", "filesystem"]
license = "Apache-2.0"

[dependencies]
clap2 = { version = "4.1.8", features = ["derive", "wrap_help"] }
dirs = "5.0.0"
error-stack = "0.3.1"
fuc_engine = "1.1.6"
rustix = { version = "0.37.3", features = ["fs", "process", "thread", "linux_latest"] }
thiserror = "1.0.40"

[dev-dependencies]
supercilex-tests = "0.3.1"
trycmd = "0.14.15"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.dr]
inherits = "release"
debug = true
strip = false
