version = "Two"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
wrap_comments = true
